### PR TITLE
Contains-faster

### PR DESCRIPTION
**Pull request by jchris**
contains can get stuck, i'm not sure how it gets a cycle, but this fixes it.

### CODE REVIEW

**Comment by alanshaw** [comment]
Need a test case for this...

**Comment by jchris** [comment]
ok, I've only seen it rarely (but then I put this patch in) I'll run without it until I see again and isolate. Maybe it makes sense to convert this to a draft PR until I have the test case?

**Comment by jchris** [comment]
this is still relevant on latest Fireproof 0.17.1 with 0.4.0, I'll try replacing the continue with a throw and see what the tests do

**Comment by jchris** [comment]
the current test throws when I change the code for that:

```
if (seen.has(link.toString())) throw new Error('cycle detected')
```


test output:

```
╰─± npm test

> @web3-storage/pail@0.4.0 test
> mocha test/*.test.js

Debugger listening on ws://127.0.0.1:53172/e2204c57-b000-4a7a-aa41-1f4b49fd2dff
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.


  batch
    ✔ batches puts (shard on key length) (198ms)
    ✔ batches puts (shard on max size) (106ms)
    ✔ create the same DAG as non-batched puts (574ms)
    ✔ error when put after commit
    ✔ error when commit after commit
Shard(bafyreiavestmnbvz3pl76wzinv4jn62q5ti2zlbx4kzoopaxpaypl5yeda) 126b
└─┬ Key(test)
  ├── Value(bafkreid7xpt47sg6fpguwblhm6bosh5c4n3gbwg66h5fdu6hdrf4y7k3lu)
  └─┬ Shard(bafyreihododc26iowbkzugg3hx6tcxzqbr4px5z3rqlv6kanvm6rhqlpza) 277b
    ├─┬ Key(ajst)
    │ └─┬ Shard(bafyreidhmtixjritambwgkk727gwsougxveykewibw6zk3neo2aks62pp4) 85b
    │   └─┬ Key(/zoo)
    │     └─┬ Shard(bafyreidu73zvsu5c2p7oonzkumsn7dyzhmauqmxvladcxzy3gd6cawj6zu) 82b
    │       └─┬ Key(-y)
    │         └── Value(bafkreieau4fjzqp7uh5472ligulmxdz7rf3y5vdbujitxng4knusw2ppji)
    ├─┬ Key(mluv)
    │ └─┬ Shard(bafyreiegspumcuyzrl5tbgilpctsq7rutzevmigqyi3onokw5ps63mfgr4) 85b
    │   └─┬ Key(hiha)
    │     └─┬ Shard(bafyreidm7r4vuqdioahsffugosi45os6ilxap7w2g2yasoucpnfx4orn74) 82b
    │       └─┬ Key(og)
    │         └── Value(bafkreifc5cpbczxycjhbnys3dbyxk6yaoxghomhjgf3exohqptxznhiukq)
    ├─┬ Key(mlux)
    │ └─┬ Shard(bafyreihnxi6v23nhy3kxznrmv3oosiqr7jiocyz7e5mxwiqpwupynbtm74) 85b
    │   └─┬ Key(ye-g)
    │     └─┬ Shard(bafyreico55w7cpcwwvb56m6pgs4vwyurq3zle5jdjlxljygot5kaitlg34) 82b
    │       └─┬ Key(uv)
    │         └── Value(bafkreiaxno6taf7fwcvb4wofz427xonynq3aaibjkn3lnts6rouz6mgxji)
    ├─┬ Key(ngug)
    │ └─┬ Shard(bafyreig7jujpkfrkrfhf2qmdkblixhdltzyywdyotw7ks627s3n3bfzsse) 85b
    │   └─┬ Key(xcfc)
    │     └─┬ Shard(bafyreieulzuyt2b47nvwg24gmuxocjuqsdlezkcotsaevdj5xuzyra6rgm) 82b
    │       └─┬ Key(fw)
    │         └── Value(bafkreicfoxkhqfmbiefjupdwmxqpl6shjkibbrepeh7hpeqiuhrhkcaqji)
    └─┬ Key(sxkc)
      └─┬ Shard(bafyreihilttwpfwryj4dko3phkrdextf3f7fissgmh2726z24u6nwy4xaa) 85b
        └─┬ Key(/z/s)
          └─┬ Shard(bafyreievma7muqg33ngytnpn7qtksvy3phkfbpgdtbfvacph4qyc7jbkiy) 82b
            └─┬ Key(ks)
              └── Value(bafkreid6dsjuvyeagjd22qlftftetto4caegnr3ek6mhpd4i5clbyycwqa)

    ✔ traverses existing shards to put values

  clock
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreifdues557vbletgonaznncz2cbqf7dyjqcfxysg7mao5mw5hkqejm [label="bafy..qejm"];
  head -> bafyreifdues557vbletgonaznncz2cbqf7dyjqcfxysg7mao5mw5hkqejm;
}
    ✔ create a new clock
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreibh5nvmsnahsp22qd55rbm7aoe5ogwqi3flw3wyiku6bfcd6xpx4y [label="bafy..px4y"];
  head -> bafyreibh5nvmsnahsp22qd55rbm7aoe5ogwqi3flw3wyiku6bfcd6xpx4y;
  bafyreibh5nvmsnahsp22qd55rbm7aoe5ogwqi3flw3wyiku6bfcd6xpx4y -> bafyreife5psg7pw5zs6hof7eecjoqwreqch2ijkvxvgilfnhr4p4k2gqly;
  node [shape=oval]; bafyreife5psg7pw5zs6hof7eecjoqwreqch2ijkvxvgilfnhr4p4k2gqly [label="bafy..gqly" fontname="Courier"];
}
    ✔ add an event
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreiagyd6gi7njtvyvvvermpih357hn4gijjqidgwz62bfj7w2qlrwa4 [label="bafy..rwa4"];
  head -> bafyreiagyd6gi7njtvyvvvermpih357hn4gijjqidgwz62bfj7w2qlrwa4;
  bafyreiagyd6gi7njtvyvvvermpih357hn4gijjqidgwz62bfj7w2qlrwa4 -> bafyreidbwabnj2re2ic2gxu3npbkjtmb5r2ewu3akwmswdbstt7emwxjhy;
  node [shape=oval fontname="Courier"]; bafyreignw7gcu7dypbi5kcwa3rlqp6g4vdsn5ulnnv75qtu5jvpfmbr4ya [label="bafy..r4ya"];
  head -> bafyreignw7gcu7dypbi5kcwa3rlqp6g4vdsn5ulnnv75qtu5jvpfmbr4ya;
  bafyreignw7gcu7dypbi5kcwa3rlqp6g4vdsn5ulnnv75qtu5jvpfmbr4ya -> bafyreidbwabnj2re2ic2gxu3npbkjtmb5r2ewu3akwmswdbstt7emwxjhy;
  node [shape=oval]; bafyreidbwabnj2re2ic2gxu3npbkjtmb5r2ewu3akwmswdbstt7emwxjhy [label="bafy..xjhy" fontname="Courier"];
}
    ✔ add two events with shared parents
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreibht75ksbilzmdhwapbzx7ordvcmcclju4exwzjaxqv736lz5ivku [label="bafy..ivku"];
  head -> bafyreibht75ksbilzmdhwapbzx7ordvcmcclju4exwzjaxqv736lz5ivku;
  bafyreibht75ksbilzmdhwapbzx7ordvcmcclju4exwzjaxqv736lz5ivku -> bafyreielccqa2fz2zeeq3yk4efwatkzqhu4auty5bz5677cit4l5pxzbgu;
  bafyreibht75ksbilzmdhwapbzx7ordvcmcclju4exwzjaxqv736lz5ivku -> bafyreiavd5fe3b2xsznzb7npld5ga2a5wijvnbmyq6buhyjgrh7pdcchtu;
  node [shape=oval fontname="Courier"]; bafyreihonqmvpylqhtu4ksxhbfn6sf5pcysx6lcimlr7dqyvepo26wffkm [label="bafy..ffkm"];
  head -> bafyreihonqmvpylqhtu4ksxhbfn6sf5pcysx6lcimlr7dqyvepo26wffkm;
  bafyreihonqmvpylqhtu4ksxhbfn6sf5pcysx6lcimlr7dqyvepo26wffkm -> bafyreia36ww674oez2h57e5bgovvwor6quofod75hmvd7ltdtrtf564cni;
  node [shape=oval]; bafyreielccqa2fz2zeeq3yk4efwatkzqhu4auty5bz5677cit4l5pxzbgu [label="bafy..zbgu" fontname="Courier"];
  bafyreielccqa2fz2zeeq3yk4efwatkzqhu4auty5bz5677cit4l5pxzbgu -> bafyreicdqz3u6yvy22szzqznoylwygjy7t2ukss6y6caossu5y43vjosoq;
  node [shape=oval]; bafyreiavd5fe3b2xsznzb7npld5ga2a5wijvnbmyq6buhyjgrh7pdcchtu [label="bafy..chtu" fontname="Courier"];
  bafyreiavd5fe3b2xsznzb7npld5ga2a5wijvnbmyq6buhyjgrh7pdcchtu -> bafyreicdqz3u6yvy22szzqznoylwygjy7t2ukss6y6caossu5y43vjosoq;
  node [shape=oval]; bafyreia36ww674oez2h57e5bgovvwor6quofod75hmvd7ltdtrtf564cni [label="bafy..4cni" fontname="Courier"];
  bafyreia36ww674oez2h57e5bgovvwor6quofod75hmvd7ltdtrtf564cni -> bafyreicdqz3u6yvy22szzqznoylwygjy7t2ukss6y6caossu5y43vjosoq;
  node [shape=oval]; bafyreicdqz3u6yvy22szzqznoylwygjy7t2ukss6y6caossu5y43vjosoq [label="bafy..osoq" fontname="Courier"];
}
    ✔ add two events with some shared parents
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreihapdyomhudmwdgj5otvd7nvpg5tgvnopjw5ez44we7w2zmnk72oq [label="bafy..72oq"];
  head -> bafyreihapdyomhudmwdgj5otvd7nvpg5tgvnopjw5ez44we7w2zmnk72oq;
  bafyreihapdyomhudmwdgj5otvd7nvpg5tgvnopjw5ez44we7w2zmnk72oq -> bafyreidxhwxi7zjr2an27qxlaxbb66ywqvwgok5tzws7y6wxt72afag4qu;
  bafyreihapdyomhudmwdgj5otvd7nvpg5tgvnopjw5ez44we7w2zmnk72oq -> bafyreicx4pvteqh5bk4dmrwofjufp4y2dcscs5uismoidkutcessxso35u;
  bafyreihapdyomhudmwdgj5otvd7nvpg5tgvnopjw5ez44we7w2zmnk72oq -> bafyreihrnzxticbswfaatadygvl6aewkjeamgprujuyyg44blxdtkllyca;
  node [shape=oval]; bafyreidxhwxi7zjr2an27qxlaxbb66ywqvwgok5tzws7y6wxt72afag4qu [label="bafy..g4qu" fontname="Courier"];
  bafyreidxhwxi7zjr2an27qxlaxbb66ywqvwgok5tzws7y6wxt72afag4qu -> bafyreibomqnwdydr5tersx3fsf7l4kzft22xkhe6gbnvyv7usy57ns3ywi;
  bafyreidxhwxi7zjr2an27qxlaxbb66ywqvwgok5tzws7y6wxt72afag4qu -> bafyreibmfqmkfwdaeyzyno3pfsotx64qdb5m3oa7qchnhchrniiwrykiqe;
  node [shape=oval]; bafyreicx4pvteqh5bk4dmrwofjufp4y2dcscs5uismoidkutcessxso35u [label="bafy..o35u" fontname="Courier"];
  bafyreicx4pvteqh5bk4dmrwofjufp4y2dcscs5uismoidkutcessxso35u -> bafyreibomqnwdydr5tersx3fsf7l4kzft22xkhe6gbnvyv7usy57ns3ywi;
  bafyreicx4pvteqh5bk4dmrwofjufp4y2dcscs5uismoidkutcessxso35u -> bafyreibmfqmkfwdaeyzyno3pfsotx64qdb5m3oa7qchnhchrniiwrykiqe;
  node [shape=oval]; bafyreihrnzxticbswfaatadygvl6aewkjeamgprujuyyg44blxdtkllyca [label="bafy..lyca" fontname="Courier"];
  bafyreihrnzxticbswfaatadygvl6aewkjeamgprujuyyg44blxdtkllyca -> bafyreibomqnwdydr5tersx3fsf7l4kzft22xkhe6gbnvyv7usy57ns3ywi;
  bafyreihrnzxticbswfaatadygvl6aewkjeamgprujuyyg44blxdtkllyca -> bafyreibmfqmkfwdaeyzyno3pfsotx64qdb5m3oa7qchnhchrniiwrykiqe;
  node [shape=oval]; bafyreibomqnwdydr5tersx3fsf7l4kzft22xkhe6gbnvyv7usy57ns3ywi [label="bafy..3ywi" fontname="Courier"];
  bafyreibomqnwdydr5tersx3fsf7l4kzft22xkhe6gbnvyv7usy57ns3ywi -> bafyreiglkxcgijqgbff2mif57zno3jdzzloozj7q5mbnpjginbul73anui;
  node [shape=oval]; bafyreibmfqmkfwdaeyzyno3pfsotx64qdb5m3oa7qchnhchrniiwrykiqe [label="bafy..kiqe" fontname="Courier"];
  bafyreibmfqmkfwdaeyzyno3pfsotx64qdb5m3oa7qchnhchrniiwrykiqe -> bafyreiglkxcgijqgbff2mif57zno3jdzzloozj7q5mbnpjginbul73anui;
  node [shape=oval]; bafyreiglkxcgijqgbff2mif57zno3jdzzloozj7q5mbnpjginbul73anui [label="bafy..anui" fontname="Courier"];
}
    ✔ converge when multi-root
    1) add an old event
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreifnsjvyzmw73k7oe3u2kbxjvv62ruahq464hcugniqww6o66sgv7y [label="bafy..gv7y"];
  head -> bafyreifnsjvyzmw73k7oe3u2kbxjvv62ruahq464hcugniqww6o66sgv7y;
  bafyreifnsjvyzmw73k7oe3u2kbxjvv62ruahq464hcugniqww6o66sgv7y -> bafyreif7u4fllrcxfmg6cvaxpluhow4n645pcbvfr5u5jaqsbdktsxbuje;
  node [shape=oval]; bafyreif7u4fllrcxfmg6cvaxpluhow4n645pcbvfr5u5jaqsbdktsxbuje [label="bafy..buje" fontname="Courier"];
  bafyreif7u4fllrcxfmg6cvaxpluhow4n645pcbvfr5u5jaqsbdktsxbuje -> bafyreihhmihiccz7o7vozewselzateohq3c4s7quob5zqaruuhuvk6grty;
  node [shape=oval]; bafyreihhmihiccz7o7vozewselzateohq3c4s7quob5zqaruuhuvk6grty [label="bafy..grty" fontname="Courier"];
}
    ✔ add an event with missing parents

  CRDT
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreibqpva2xqb3qusvhv43wtcl43veyer4ydobjshioje33razsyv5u4 [label="bafy..v5u4\nput(key, bafk..jpwm)"];
  head -> bafyreibqpva2xqb3qusvhv43wtcl43veyer4ydobjshioje33razsyv5u4;
}
    ✔ put a value to a new clock
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreidky5isovm2axle2bli7xksqvco4mg7w5kzxj7t67h4v3yb7f6nx4 [label="bafy..6nx4\nput(key1, bafk..eupa)"];
  head -> bafyreidky5isovm2axle2bli7xksqvco4mg7w5kzxj7t67h4v3yb7f6nx4;
  bafyreidky5isovm2axle2bli7xksqvco4mg7w5kzxj7t67h4v3yb7f6nx4 -> bafyreieaic25rphaztg4wc35d4dgfh2ssdttrcl6txfmbegxs2ocdeprga;
  node [shape=oval]; bafyreieaic25rphaztg4wc35d4dgfh2ssdttrcl6txfmbegxs2ocdeprga [label="bafy..prga\nput(key0, bafk..oqa4)" fontname="Courier"];
}
    ✔ linear put multiple values
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreihmkn2jklcwzcl3thfmxvayfbdhtdsm5y6ko356lc37io5jyqawh4 [label="bafy..awh4\nput(pear, bafk..v2hi)"];
  head -> bafyreihmkn2jklcwzcl3thfmxvayfbdhtdsm5y6ko356lc37io5jyqawh4;
  bafyreihmkn2jklcwzcl3thfmxvayfbdhtdsm5y6ko356lc37io5jyqawh4 -> bafyreifb42b47bkp7spink7dkhkuwtbth74nz7j4lpjcwdpsbxgscberay;
  bafyreihmkn2jklcwzcl3thfmxvayfbdhtdsm5y6ko356lc37io5jyqawh4 -> bafyreieiitbmv7acf6nxzng6u4xcg37mctwcsp5wvnrfyeghygjrth65tq;
  bafyreihmkn2jklcwzcl3thfmxvayfbdhtdsm5y6ko356lc37io5jyqawh4 -> bafyreicc4rakg7qnoyntq5qeelva2uhjkgyi3xioajk66lss4yekxl3hwm;
  node [shape=oval]; bafyreifb42b47bkp7spink7dkhkuwtbth74nz7j4lpjcwdpsbxgscberay [label="bafy..eray\nput(banana, bafk..h2p4)" fontname="Courier"];
  bafyreifb42b47bkp7spink7dkhkuwtbth74nz7j4lpjcwdpsbxgscberay -> bafyreiegrmhiwyv7yqzdtyofybci2gytr2fh726wedylzldu5yatavvkjq;
  node [shape=oval]; bafyreieiitbmv7acf6nxzng6u4xcg37mctwcsp5wvnrfyeghygjrth65tq [label="bafy..65tq\nput(orange, bafk..bjly)" fontname="Courier"];
  bafyreieiitbmv7acf6nxzng6u4xcg37mctwcsp5wvnrfyeghygjrth65tq -> bafyreiawwpl6lsm3owsr5uvf7ysisxmnn5j7m3hkbvfqdxohtdmxeqp654;
  node [shape=oval]; bafyreicc4rakg7qnoyntq5qeelva2uhjkgyi3xioajk66lss4yekxl3hwm [label="bafy..3hwm\nput(mango, bafk..kzni)" fontname="Courier"];
  bafyreicc4rakg7qnoyntq5qeelva2uhjkgyi3xioajk66lss4yekxl3hwm -> bafyreiawwpl6lsm3owsr5uvf7ysisxmnn5j7m3hkbvfqdxohtdmxeqp654;
  node [shape=oval]; bafyreiegrmhiwyv7yqzdtyofybci2gytr2fh726wedylzldu5yatavvkjq [label="bafy..vkjq\nput(apple, bafk..e4ie)" fontname="Courier"];
  node [shape=oval]; bafyreiawwpl6lsm3owsr5uvf7ysisxmnn5j7m3hkbvfqdxohtdmxeqp654 [label="bafy..p654\nput(kiwi, bafk..eemu)" fontname="Courier"];
  bafyreiawwpl6lsm3owsr5uvf7ysisxmnn5j7m3hkbvfqdxohtdmxeqp654 -> bafyreiegrmhiwyv7yqzdtyofybci2gytr2fh726wedylzldu5yatavvkjq;
}
    ✔ simple parallel put multiple values
    ✔ get from multi event head
    ✔ entries from multi event head
    ✔ put same value to existing key

  CRDT batch
    ✔ error when put after commit
    ✔ error when commit after commit
digraph clock {
  node [shape=point fontname="Courier"]; head;
  node [shape=oval fontname="Courier"]; bafyreicxofsoo57qz7qx4xnbtkkaq4mmrgjmgtlonfekyjpifvnwnqmhta [label="bafy..mhta\nput(testtfidbnkzbh, bafk..lrum)"];
  head -> bafyreicxofsoo57qz7qx4xnbtkkaq4mmrgjmgtlonfekyjpifvnwnqmhta;
  bafyreicxofsoo57qz7qx4xnbtkkaq4mmrgjmgtlonfekyjpifvnwnqmhta -> bafyreicq6w3r6mmzicchy5dpi32ow7zj3dwbakbujmaazjufmyd37dewxm;
  node [shape=oval]; bafyreicq6w3r6mmzicchy5dpi32ow7zj3dwbakbujmaazjufmyd37dewxm [label="bafy..ewxm\nput(testtfidbnkzbh, bafk..377u)\nput(testhmjmklvmde, bafk..tlme)\nput(testaxwaqajmej, bafk..4b2e)\nput(testnkesxrumyt, bafk..zcsq)\nput(testruozyjcfmu, bafk..w6ky)\nput(test_w_qjb//si, bafk..hg3q)\nput(testo_gztkrpxn, bafk..skvq)\nput(testxqbokhdjzt, bafk..cn4q)\nput(testbpkony-ygh, bafk..fgii)\nput(testijldbupyap, bafk..opxy)\n...15 more" fontname="Courier"];
  bafyreicq6w3r6mmzicchy5dpi32ow7zj3dwbakbujmaazjufmyd37dewxm -> bafyreiaanudo2pkhkhk7ew7pd454op63kfwzdm6kmjpl6tkuldnums43zm;
  node [shape=oval]; bafyreiaanudo2pkhkhk7ew7pd454op63kfwzdm6kmjpl6tkuldnums43zm [label="bafy..43zm\nput(test0, bafk..adda)" fontname="Courier"];
}
    ✔ linear put with batch

  del
    ✔ deletes a value

  diff
    ✔ diffs a non-sharded addition

  entries
    ✔ lists entries in lexicographical order
    ✔ lists entries by prefix

  get
    ✔ get from root shard
    ✔ returns undefined when not found

  put
    ✔ put to empty shard
    ✔ put same value to existing key
    ✔ auto-shards on long key
    ✔ auto-shards on super long key
    ✔ shards at size limit


  32 passing (930ms)
  1 failing

  1) clock
       add an old event:
     Error: cycle detected
      at contains (file:///Users/jchris/Documents/GitHub/pail/src/clock/index.js:133:42)
      at async advance (file:///Users/jchris/Documents/GitHub/pail/src/clock/index.js:35:9)
      at async Context.<anonymous> (file:///Users/jchris/Documents/GitHub/pail/test/clock.test.js:187:12)

```

**Pull request closed without merging**
